# coding: utf-8

"""
    EAI Toolkit

    EAI Toolkit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ListResponseMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'limit': 'int',
        'offset': 'int',
        'q': 'str',
        'total': 'int'
    }

    attribute_map = {
        'limit': 'limit',
        'offset': 'offset',
        'q': 'q',
        'total': 'total'
    }

    def __init__(self, limit=None, offset=None, q=None, total=None):  # noqa: E501
        """ListResponseMetadata - a model defined in OpenAPI"""  # noqa: E501

        self._limit = None
        self._offset = None
        self._q = None
        self._total = None
        self.discriminator = None

        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset
        if q is not None:
            self.q = q
        if total is not None:
            self.total = total

    @property
    def limit(self):
        """Gets the limit of this ListResponseMetadata.  # noqa: E501

        Query limit  # noqa: E501

        :return: The limit of this ListResponseMetadata.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ListResponseMetadata.

        Query limit  # noqa: E501

        :param limit: The limit of this ListResponseMetadata.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this ListResponseMetadata.  # noqa: E501

        Starting offset of the query  # noqa: E501

        :return: The offset of this ListResponseMetadata.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ListResponseMetadata.

        Starting offset of the query  # noqa: E501

        :param offset: The offset of this ListResponseMetadata.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def q(self):
        """Gets the q of this ListResponseMetadata.  # noqa: E501

        Original query (unused for the time being)  # noqa: E501

        :return: The q of this ListResponseMetadata.  # noqa: E501
        :rtype: str
        """
        return self._q

    @q.setter
    def q(self, q):
        """Sets the q of this ListResponseMetadata.

        Original query (unused for the time being)  # noqa: E501

        :param q: The q of this ListResponseMetadata.  # noqa: E501
        :type: str
        """

        self._q = q

    @property
    def total(self):
        """Gets the total of this ListResponseMetadata.  # noqa: E501

        Total number of matching resources  # noqa: E501

        :return: The total of this ListResponseMetadata.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ListResponseMetadata.

        Total number of matching resources  # noqa: E501

        :param total: The total of this ListResponseMetadata.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListResponseMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
