# coding: utf-8

"""
    EAI Toolkit

    EAI Toolkit API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Service(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'access_url': 'str',
        'account': 'FieldAccount',
        'created': 'str',
        'creator': 'FieldCreator',
        'full_name': 'str',
        'id': 'str',
        'name': 'str',
        'organization': 'FieldOrganization',
        'port': 'int',
        'role': 'OneOfstringUUID',
        'runtime': 'OneOfstringUUID',
        'status': 'str',
        'tags': 'list[object]',
        'urn': 'str'
    }

    attribute_map = {
        'access_url': 'accessURL',
        'account': 'account',
        'created': 'created',
        'creator': 'creator',
        'full_name': 'fullName',
        'id': 'id',
        'name': 'name',
        'organization': 'organization',
        'port': 'port',
        'role': 'role',
        'runtime': 'runtime',
        'status': 'status',
        'tags': 'tags',
        'urn': 'urn'
    }

    def __init__(self, access_url=None, account=None, created=None, creator=None, full_name=None, id=None, name=None, organization=None, port=8080, role=None, runtime=None, status='on', tags=None, urn=None):  # noqa: E501
        """Service - a model defined in OpenAPI"""  # noqa: E501

        self._access_url = None
        self._account = None
        self._created = None
        self._creator = None
        self._full_name = None
        self._id = None
        self._name = None
        self._organization = None
        self._port = None
        self._role = None
        self._runtime = None
        self._status = None
        self._tags = None
        self._urn = None
        self.discriminator = None

        if access_url is not None:
            self.access_url = access_url
        self.account = account
        self.created = created
        self.creator = creator
        if full_name is not None:
            self.full_name = full_name
        self.id = id
        if name is not None:
            self.name = name
        self.organization = organization
        if port is not None:
            self.port = port
        if role is not None:
            self.role = role
        if runtime is not None:
            self.runtime = runtime
        if status is not None:
            self.status = status
        if tags is not None:
            self.tags = tags
        self.urn = urn

    @property
    def access_url(self):
        """Gets the access_url of this Service.  # noqa: E501

        URL generated to access to the service  # noqa: E501

        :return: The access_url of this Service.  # noqa: E501
        :rtype: str
        """
        return self._access_url

    @access_url.setter
    def access_url(self, access_url):
        """Sets the access_url of this Service.

        URL generated to access to the service  # noqa: E501

        :param access_url: The access_url of this Service.  # noqa: E501
        :type: str
        """

        self._access_url = access_url

    @property
    def account(self):
        """Gets the account of this Service.  # noqa: E501


        :return: The account of this Service.  # noqa: E501
        :rtype: FieldAccount
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Service.


        :param account: The account of this Service.  # noqa: E501
        :type: FieldAccount
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def created(self):
        """Gets the created of this Service.  # noqa: E501


        :return: The created of this Service.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Service.


        :param created: The created of this Service.  # noqa: E501
        :type: str
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def creator(self):
        """Gets the creator of this Service.  # noqa: E501


        :return: The creator of this Service.  # noqa: E501
        :rtype: FieldCreator
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this Service.


        :param creator: The creator of this Service.  # noqa: E501
        :type: FieldCreator
        """
        if creator is None:
            raise ValueError("Invalid value for `creator`, must not be `None`")  # noqa: E501

        self._creator = creator

    @property
    def full_name(self):
        """Gets the full_name of this Service.  # noqa: E501


        :return: The full_name of this Service.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this Service.


        :param full_name: The full_name of this Service.  # noqa: E501
        :type: str
        """
        if full_name is not None and not re.search(r'^|[a-z0-9_]+(\.[a-z0-9_]+)*$', full_name):  # noqa: E501
            raise ValueError(r"Invalid value for `full_name`, must be a follow pattern or equal to `/^|[a-z0-9_]+(\.[a-z0-9_]+)*$/`")  # noqa: E501

        self._full_name = full_name

    @property
    def id(self):
        """Gets the id of this Service.  # noqa: E501

        Unique id of the resource  # noqa: E501

        :return: The id of this Service.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Service.

        Unique id of the resource  # noqa: E501

        :param id: The id of this Service.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Service.  # noqa: E501


        :return: The name of this Service.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Service.


        :param name: The name of this Service.  # noqa: E501
        :type: str
        """
        if name is not None and not re.search(r'^[a-z0-9_]*$', name):  # noqa: E501
            raise ValueError(r"Invalid value for `name`, must be a follow pattern or equal to `/^[a-z0-9_]*$/`")  # noqa: E501

        self._name = name

    @property
    def organization(self):
        """Gets the organization of this Service.  # noqa: E501


        :return: The organization of this Service.  # noqa: E501
        :rtype: FieldOrganization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Service.


        :param organization: The organization of this Service.  # noqa: E501
        :type: FieldOrganization
        """
        if organization is None:
            raise ValueError("Invalid value for `organization`, must not be `None`")  # noqa: E501

        self._organization = organization

    @property
    def port(self):
        """Gets the port of this Service.  # noqa: E501

        Port used by the job  # noqa: E501

        :return: The port of this Service.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this Service.

        Port used by the job  # noqa: E501

        :param port: The port of this Service.  # noqa: E501
        :type: int
        """
        if port is not None and port > 65525:  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value less than or equal to `65525`")  # noqa: E501
        if port is not None and port < 1025:  # noqa: E501
            raise ValueError("Invalid value for `port`, must be a value greater than or equal to `1025`")  # noqa: E501

        self._port = port

    @property
    def role(self):
        """Gets the role of this Service.  # noqa: E501

        Role resource associated to the service  # noqa: E501

        :return: The role of this Service.  # noqa: E501
        :rtype: OneOfstringUUID
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Service.

        Role resource associated to the service  # noqa: E501

        :param role: The role of this Service.  # noqa: E501
        :type: OneOfstringUUID
        """

        self._role = role

    @property
    def runtime(self):
        """Gets the runtime of this Service.  # noqa: E501

        Data resource associated to the service which contains runtime spec  # noqa: E501

        :return: The runtime of this Service.  # noqa: E501
        :rtype: OneOfstringUUID
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this Service.

        Data resource associated to the service which contains runtime spec  # noqa: E501

        :param runtime: The runtime of this Service.  # noqa: E501
        :type: OneOfstringUUID
        """

        self._runtime = runtime

    @property
    def status(self):
        """Gets the status of this Service.  # noqa: E501

        Status of the service. \"on\" to enable it and \"off\" to disable it  # noqa: E501

        :return: The status of this Service.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Service.

        Status of the service. \"on\" to enable it and \"off\" to disable it  # noqa: E501

        :param status: The status of this Service.  # noqa: E501
        :type: str
        """
        allowed_values = ["on", "off"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def tags(self):
        """Gets the tags of this Service.  # noqa: E501

        Tags of the resource  # noqa: E501

        :return: The tags of this Service.  # noqa: E501
        :rtype: list[object]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Service.

        Tags of the resource  # noqa: E501

        :param tags: The tags of this Service.  # noqa: E501
        :type: list[object]
        """

        self._tags = tags

    @property
    def urn(self):
        """Gets the urn of this Service.  # noqa: E501

        URN of the resource  # noqa: E501

        :return: The urn of this Service.  # noqa: E501
        :rtype: str
        """
        return self._urn

    @urn.setter
    def urn(self, urn):
        """Sets the urn of this Service.

        URN of the resource  # noqa: E501

        :param urn: The urn of this Service.  # noqa: E501
        :type: str
        """
        if urn is None:
            raise ValueError("Invalid value for `urn`, must not be `None`")  # noqa: E501
        if urn is not None and not re.search(r'^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:(account|policy|role|user|team):[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:(data|job|service|role|policy):[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?)?$', urn):  # noqa: E501
            raise ValueError(r"Invalid value for `urn`, must be a follow pattern or equal to `/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:(account|policy|role|user|team):[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:(data|job|service|role|policy):[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?)?$/`")  # noqa: E501

        self._urn = urn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Service):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
